Update patch set 1
Patch Set 1: Verified; Looks good to me, approved

This is a revert. The original change broke the build (and I thought I had double-checked it...)

Build failure:
out/target/product/generic/obj/EXECUTABLES/racoon_intermediates/src/racoon/crypto_openssl.o: In function `eay_init':
external/ipsec-tools/src/racoon/crypto_openssl.c:2566: undefined reference to `ENGINE_load_builtin_engines'
external/ipsec-tools/src/racoon/crypto_openssl.c:2567: undefined reference to `ENGINE_register_all_complete'

Patch-set: 1
Reviewer: Jean-Baptiste Queru <1000660@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Code-Review=+2
Label: Verified=+1